server:
  port: 6065

spring:
  application:
    name: reviews-service

  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:D:/research/dataset/database.sqlite
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect

#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
  kafka:
    bootstrap-servers: 9092
    consumer:
      group-id: pitchfork
      auto-offset-reset: earliest
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      value-serializer: org.apache.kafka.common.serialization.StringDeserializer
      key-serializer: org.apache.kafka.common.serialization.StringDeserializer

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8061/eureka}
  instance:
    preferIpAddress: true